name: "Fuzz: boka"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/boka-fuzz.yml'

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: boka
      docker_image: 'acala/boka:latest'
      docker_cmd: 'fuzz target --socket-path {TARGET_SOCK}'
